migrate bundling script to globSync
similar to the last commit, move from the old default export in a
bundling script to use `globSync`. this time when we build, we get a new
error:

```
[!] (plugin commonjs) SyntaxError: Unexpected token (50:4) in /Users/ryan/workspaces/stencil/node_modules/glob/dist/mjs/walker.js
node_modules/glob/dist/mjs/walker.js (50:4)
48:         }
49:     }
50:     #ignored(path) {
        ^
51:         return this.seen.has(path) || !!this.#ignore?.ignored?.(path);
52:     }
SyntaxError: Unexpected token (50:4) in /Users/ryan/workspaces/stencil/node_modules/glob/dist/mjs/walker.js
    at Parser.pp$4.raise (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:15592:13)
    at Parser.pp.unexpected (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:13284:8)
    at Parser.pp$3.parseIdent (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:15543:10)
    at Parser.parseIdent (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:19589:27)
    at Parser.parseIdent (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:19671:27)
    at Parser.pp$3.parsePropertyName (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:15351:105)
    at Parser.parsePropertyName (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:19665:15)
    at Parser.pp$1.parseClassElement (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:13959:27)
    at Parser.parseClassElement (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:19584:38)
    at Parser.parseClassElement (/Users/ryan/workspaces/stencil/node_modules/rollup/dist/shared/rollup.js:19617:40)

```

the commonjs plugin doesn't know how to handle private tokens ('#').